/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudjavaswingeisg;

import javax.swing.JOptionPane;
import utilerias.OpcionesCRUD;
import accesoadatos.CursoDAL;
import entidades.Curso;


/**
 *
 * @author Chello
 */
public class FrmCursosEsc extends javax.swing.JFrame {

    private OpcionesCRUD opcionCRUD;
    private Curso cursoActual = new Curso();

    /**
     * Creates new form FrmCursosEsc
     */
    public FrmCursosEsc(OpcionesCRUD opcion,Curso curso) {
        this.opcionCRUD = opcion;
        initComponents();
        if (opcion != OpcionesCRUD.CREAR) {
            asingarDatos(curso);
            cursoActual = curso;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtADescripcion = new javax.swing.JTextArea();
        jTxtDuracion = new javax.swing.JTextField();
        jTxtPrecio = new javax.swing.JTextField();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setTitle("Cursos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre*");

        jLabel2.setText("Descripcion(opcional)");

        jLabel3.setText("Duración(hrs)*");

        jLabel4.setText("Precio*");

        jTxtADescripcion.setColumns(20);
        jTxtADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTxtADescripcion);

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnGuardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnCancelar))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addComponent(jTxtDuracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarDatos() {
        boolean valid = true;

        if (jTxtNombre.getText().isEmpty()) {
            valid = false;
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio", "Validar campo", JOptionPane.WARNING_MESSAGE);
        }

        if (jTxtDuracion.getText().isEmpty()) {
            valid = false;
            JOptionPane.showMessageDialog(this, "La duracion es obligatoria", "Validar campo", JOptionPane.WARNING_MESSAGE);
        }
        if (jTxtPrecio.getText().isEmpty()) {
            valid = false;
            JOptionPane.showMessageDialog(this, "El precio es obligatorio", "Validar campo", JOptionPane.WARNING_MESSAGE);
        }

        return valid;
    }

    private Curso obtenerDatos() {
        Curso curso = new Curso();
        curso.setNombre(jTxtNombre.getText());
        curso.setDescripcion(jTxtADescripcion.getText());
        curso.setDuracion(Integer.parseInt(jTxtDuracion.getText()));
        curso.setPrecio(Double.parseDouble(jTxtPrecio.getText()));
        curso.setCursoID(cursoActual.getCursoID());
        return curso;
    }

    private void asingarDatos(Curso curso) {
        jTxtNombre.setText(curso.getNombre());
        jTxtADescripcion.setText(curso.getDescripcion());
        jTxtDuracion.setText(Integer.toString(curso.getDuracion()));
        jTxtPrecio.setText(Double.toString(curso.getPrecio()));

    }

    private void crearReg() {
        try {
            Curso curso = obtenerDatos();
            int result = CursoDAL.crear(curso);
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "El curso fue registrado existosamente", "CREAR CURSO",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Sucedio un error al crear el curso", "ERROR CURSO",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR CURSO",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void modificarReg() {
        try {
            Curso curso = obtenerDatos();
            int result = CursoDAL.modificar(curso);
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "El curso fue modificado existosamente", "MODIFICAR CURSO",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Sucedio un error al modificar el curso", "ERROR CURSO",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR CURSO",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void eliminarReg() {
        try {
            Curso curso = obtenerDatos();
            int result = CursoDAL.eliminar(curso);
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "El curso fue eliminado existosamente", "ELIMINAR CURSO",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Sucedio un error al eliminar el curso", "ERROR CURSO",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERROR CURSO",
                    JOptionPane.ERROR_MESSAGE);
        }

    }
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        FrmCursosLec frmCursosLec = new FrmCursosLec();
        if (validarDatos()) {
            if (null != opcionCRUD) {
                switch (opcionCRUD) {
                    case CREAR:
                        crearReg();
                        frmCursosLec.setVisible(true);
                        this.setVisible(false);
                        break;
                    case MODIFICAR:
                        modificarReg();
                        frmCursosLec.setVisible(true);
                        this.setVisible(false);
                        break;
                    case ELIMINAR:
                        eliminarReg();
                        frmCursosLec.setVisible(true);
                        this.setVisible(false);
                        break;
                    default:
                        break;
                }
            }
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        FrmCursosLec frmCursosLec = new FrmCursosLec();
        frmCursosLec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        FrmCursosLec frmCursosLec = new FrmCursosLec();
        frmCursosLec.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtADescripcion;
    private javax.swing.JTextField jTxtDuracion;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtPrecio;
    // End of variables declaration//GEN-END:variables
}
