CREATE DATABASE CRUDJavaSwingEISGDB

USE CRUDJavaSwingEISGDB

CREATE TABLE Cursos (
CursoID INT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(200) NOT NULL,
Descripcion VARCHAR(500),
Duracion INT NOT NULL,
Precio DECIMAL(10,2) NOT NULL
);

CREATE TABLE Inscripciones (
InscripcionID INT PRIMARY KEY IDENTITY(1,1),
FechaInscripcion DATE NOT NULL,
CursoID INT NOT NULL,
EstudianteNombre VARCHAR(100) NOT NULL,
EstudianteCorreo VARCHAR(100) NOT NULL,
CONSTRAINT FK_Inscripciones_Cursos FOREIGN KEY (CursoID) REFERENCES Cursos(CursoID)
);